
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: central
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: fastapi-backend
        ports:
        - containerPort: 8000
